### ISSUE TITLE
Lines not delimited by CRLF sequence near line # 1

### ISSUE THREAD

**Issue by paradeiser** [jdejaegh/ics-fusion#3]
Dear Dev-Team,

I appreciate your code, I just have issues validating the generated ics stream.
When running my ics-fusion calendar thru
https://icalendar.org/validator.html

I get the following result:
```
Problem! Found 1 error

Errors
Lines not delimited by CRLF sequence [near line # 1](javascript:void(0);)Reference: [RFC 5545 3.1. Content Lines](http://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html)
```

the source data looks like:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
BEGIN:VEVENT
CREATED:20220309T232834Z
DTSTART;VALUE=DATE:20211217
DTEND;VALUE=DATE:20211218
DTSTAMP:20220324T130010Z
DESCRIPTION:Cached at 2022-03-24 13:00:10
LAST-MODIFIED:20220310T234338Z
…
```

after I clear all cache files (app/cache/\*.\* ) and restart ics-fusion the ics file is validated just fine.
but after a couple of minutes it starts to generate the error.

I use ics-fusion to merge 11 different ics subscriptions.

thanks for your work,
paradeiser

**Comment by jdejaegh** [comment]
Hello @paradeiser,

Thanks for you interest in this project!

I was able to reproduce the bug on my side with an .ics feed.  Indeed, the validator works just fine if I clear the cache but once the application starts serving the cached file I get the same error.

I'll commit the changes and close the issue.

Thanks for your report,
Jules
